/**
 * 301s for the old Joomla/K2 URLs under /{en|de}/ukazky-nasich-vyrobku/…
 * (the Czech ones are static rules in _redirects; together they would exceed
 * Cloudflare's 2,000-rule limit). The piece map is generated by scripts/postbuild.ts.
 */
import map from './legacy-map.json';
import { pathFor, type CategoryId } from '../../src/i18n/routes';
import type { Lang } from '../../src/i18n/locales';

const pieces = map.pieces as Record<string, { category: CategoryId; slug: string }>;
const oldCats = map.oldCats as Record<string, CategoryId>;

export function legacyTarget(pathname: string, lang: Lang): string {
  const parts = pathname.split('/').filter(Boolean); // [lang, 'ukazky-nasich-vyrobku', oldCat?, 'item', '677-slug']
  const item = pathname.match(/\/item\/(\d+)-/);
  if (item && pieces[item[1]]) {
    const p = pieces[item[1]];
    return pathFor({ type: 'piece', category: p.category, no: Number(item[1]), slug: p.slug }, lang);
  }
  const cat = parts[2] && oldCats[parts[2]];
  if (cat) return pathFor({ type: 'category', category: cat }, lang);
  return pathFor({ type: 'archive' }, lang);
}

export const legacyHandler =
  (lang: Lang): PagesFunction =>
  ({ request }) => {
    const url = new URL(request.url);
    return Response.redirect(url.origin + legacyTarget(url.pathname, lang), 301);
  };
