/**
 * Runs after `astro build`. Generates the Cloudflare Pages control files from the content:
 *
 *   dist/_redirects               301s from the old Joomla URLs (Czech items, categories, poptávka)
 *   dist/_routes.json             which paths invoke Pages Functions
 *   dist/_headers                 caching and security headers
 *   functions/_lib/legacy-map.json  piece map for the EN/DE legacy redirect function
 *
 * Cloudflare allows 2,000 static + 100 dynamic redirect rules; 702 items × 3 languages
 * would not fit, so EN/DE item URLs are answered by functions/{en,de}/ukazky-nasich-vyrobku.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import products from '../content/products.json' with { type: 'json' };
import { pathFor, pieceSlug, type CategoryId } from '../src/i18n/routes';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');

interface PieceJson {
  no: number;
  title: string;
  category: CategoryId;
  oldUrls?: Record<string, string>;
}

const dir = join(ROOT, 'src/content/pieces');
const pieces: PieceJson[] = await Promise.all(
  (await readdir(dir)).filter((f) => f.endsWith('.json')).map(async (f) => JSON.parse(await readFile(join(dir, f), 'utf8'))),
);
pieces.sort((a, b) => b.no - a.no);
const oldCats = Object.fromEntries(products.products.map((p) => [p.oldCat, p.id as CategoryId]));

// ---------------------------------------------------------------- _redirects
const staticRules: string[] = [];
const dynamicRules: string[] = [];
const rule = (from: string, to: string) => `${from} ${to} 301`;

staticRules.push(rule('/poptavka', pathFor({ type: 'quote' }, 'cs')));
staticRules.push(rule('/en/poptavka', pathFor({ type: 'quote' }, 'en')));
staticRules.push(rule('/de/poptavka', pathFor({ type: 'quote' }, 'de')));
staticRules.push(rule('/cs/ukazky-nasich-vyrobku', pathFor({ type: 'archive' }, 'cs')));
for (const [oldCat, category] of Object.entries(oldCats)) {
  staticRules.push(rule(`/cs/ukazky-nasich-vyrobku/${oldCat}`, pathFor({ type: 'category', category }, 'cs')));
}
const seen = new Set<string>();
for (const p of pieces) {
  const old = p.oldUrls?.cs;
  if (!old) continue;
  const from = new URL(old).pathname.replace(/\/$/, '');
  if (seen.has(from)) continue;
  seen.add(from);
  staticRules.push(rule(from, pathFor({ type: 'piece', category: p.category, no: p.no, slug: pieceSlug(p.no, p.title) }, 'cs')));
}
// Fallbacks for sub-category listings (itemlist/category/…) and anything else under the old catalogue.
for (const [oldCat, category] of Object.entries(oldCats)) {
  dynamicRules.push(rule(`/cs/ukazky-nasich-vyrobku/${oldCat}/*`, pathFor({ type: 'category', category }, 'cs')));
}
dynamicRules.push(rule('/cs/ukazky-nasich-vyrobku/*', pathFor({ type: 'archive' }, 'cs')));

if (staticRules.length > 2000 || dynamicRules.length > 100) {
  throw new Error(`Too many redirect rules: ${staticRules.length} static, ${dynamicRules.length} dynamic`);
}
await writeFile(
  join(DIST, '_redirects'),
  `# Generated by scripts/postbuild.ts — do not edit.\n# Old Joomla URLs → new site. EN/DE catalogue URLs are handled by Pages Functions.\n${staticRules.join('\n')}\n${dynamicRules.join('\n')}\n`,
);

// ---------------------------------------------------------------- legacy map
const legacy = {
  oldCats,
  pieces: Object.fromEntries(pieces.map((p) => [String(p.no), { category: p.category, slug: pieceSlug(p.no, p.title) }])),
};
await writeFile(join(ROOT, 'functions/_lib/legacy-map.json'), JSON.stringify(legacy) + '\n');

// ---------------------------------------------------------------- _routes.json
await writeFile(
  join(DIST, '_routes.json'),
  JSON.stringify(
    {
      version: 1,
      include: ['/', '/api/*', '/en/ukazky-nasich-vyrobku', '/en/ukazky-nasich-vyrobku/*', '/de/ukazky-nasich-vyrobku', '/de/ukazky-nasich-vyrobku/*'],
      exclude: [],
    },
    null,
    2,
  ) + '\n',
);

// ---------------------------------------------------------------- _headers
await writeFile(
  join(DIST, '_headers'),
  `/*
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  X-Frame-Options: SAMEORIGIN

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/og/*
  Cache-Control: public, max-age=86400
`,
);

console.log(`postbuild: ${staticRules.length} static + ${dynamicRules.length} dynamic redirects, ${pieces.length} pieces in legacy map`);
